### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop. in WSL2 Ubuntu-20.04

### ISSUE THREAD

**Issue by mudittiwari2000** [CAIDA/bgpstream#106]
Hello!

I was hoping I could get some help, i'm currently attending a course on C++, and there we are asked to use WSL to make the codes and run them, so according to there instructions when I located to the directory where I created three files (cube.h, cube.cpp, main.cpp) , just as shown in the instructions.
Later, we were supposed to enter "make" in the terminal, and after that we were asked to write "./main", but when I wrote 'make' there, the error: "**make: *** No targets specified and no makefile found.  Stop.**" showed up, I searched for a while then decided to post an issue about it here, this is my first time ever posting an issue, so let me know if I wrote anything unnecessary or maybe if I have missed something. Thanks :)

![Screenshot (2)](https://user-images.githubusercontent.com/61103986/84845361-185d2180-b06a-11ea-8b58-1e2eaa1ca4ba.png)

Here, in the screenshot above, it shows I even tried what some people suggested i.e., to use "./configure" to create a 'makefile' for the 'make' command to find. But nothing works for me. My program runs flawlessly in VScode WIndows though.

**Comment by alistairking** [comment]
Closing as this doesn't seem to be related in any way to libbgpstream or BGPStream.
Please re-open if I'm mistaken.
