### ISSUE TITLE
RIS RIB files are inaccessible via bgpstream

### ISSUE THREAD

**Issue by romain-fontugne** [CAIDA/bgpstream#111]
Hi,
For about a week now, I cannot get RIB files from a lot of RIS collectors. The dump are still available on RIPE servers but it seems that they are not indexed by bgpstream.
This problem is also shown on caida data provider page: https://bgpstream.caida.org/data#!ris

no problem with update files though..?

**Comment by digizeph** [comment]
Hi @romain-fontugne thank you for noticing this matter! I have fixed this issue, and data access should be back now. Can you double check at your end?

**Comment by romain-fontugne** [comment]
Thanks @digizeph it is now working for me! :+1:
