### ISSUE TITLE
broker.bgpstream.caida.org/v2 is not available

### ISSUE THREAD

**Issue by AselToktogulova** [CAIDA/bgpstream#112]
Hello community,

today, the service is not available, could not find any information about it. How long is the expectation of the non-availability

thanks a lot and best regards

**Comment by digizeph** [comment]
Hi @AselToktogulova, CAIDA experienced a network outage a few hours ago that caused the downtime for the broker. The service should be back online now. I will close this issue now. Please feel free to reopen it  if you have further issues on using the broker. 

Thanks
