### ISSUE TITLE
BGPReader IP version filter for BPG updates

### ISSUE THREAD

**Issue by fmmazz** [CAIDA/bgpstream#113]
I am looking for the possibility to use BGPReader on MRT files and filter the updates based on the IP version of the prefixes (e.g., get only updates for IPv4 prefixes). Is there any filters for that? I couldn't find any on the BGPReader docs.

thanks!

**Comment by digizeph** [comment]
Yeah, there is a filter for it: https://github.com/CAIDA/libbgpstream/blob/master/FILTERING#L51

`bgpreader -f "ipv 6"`
Tested using [bgpstream v2](https://github.com/CAIDA/libbgpstream) (the recommended version to use).
