### ISSUE TITLE
make: *** No targets specified and no makefile found. Stop.

### ISSUE THREAD

**Issue by alicetan01** [CAIDA/bgpstream#114]
Hi, 

Currently i am install HPLIP to linux redhat server. 
When i run the ./configure step i get the output as below. 

[root@localhost hplip-3.12.6]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether the C++ compiler works... no
configure: error: in `/opt/hplip-3.12.6':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

Then i try to issue the "make" command, but i hit the error as below.
"make: *** No targets specified and no makefile found.  Stop."

I try to look for the Makefile and i found that there is no any Makefile, it only have the Makefile.am and Makefile,in. 

Anyone having the same issue and having any solution for this? 
appreciate the advise for the solution. 

Thank You.

**Comment by digizeph** [comment]
I believe you're in the wrong repo.

**Comment by alicetan01** [comment]
> I believe you're in the wrong repo.

May i know that how to check the repo and which repo i should use?

Thank You.
