### ISSUE TITLE
braces in as-path

### ISSUE THREAD

**Issue by lambdax-x** [CAIDA/bgpstream#12]
Got a this kind of as-path when using using bgpstream: "9002 2914 174 13188 {200013}".
Is that normal that ASn are sometimes inside braces?

**Comment by waehlisch** [comment]
Braces should represent an AS Set, which is generated when routes are aggregated. In this case, ASes are not ordered.

**Comment by lambda-voodoo** [comment]
Thank you. Is it specified somewhere in the BGPStream documentation? Because I can't find it.

**Comment by waehlisch** [comment]
Good question, I don't find it either in the documentation. But using braces to represent a set is very common (also in the routing context) ;).

**Comment by lambda-voodoo** [comment]
Using libBGPStream it is clear what type of path to process because of `bgpstream_as_path_seg_type_t`. String format of libBGPStream's `bgpstream_as_path_seg_snprintf` or _pybgpstream's `as-path` field of a BGPElem should be documented in my opinion.

**Comment by alistairking** [comment]
Thats a really good point. I'll make sure we add some documentation for the next release.

**Comment by alistairking** [comment]
This is addressed in PR #39
