### ISSUE TITLE
Segfault in pybgpstream when accessing data interfaces

### ISSUE THREAD

**Issue by zorun** [CAIDA/bgpstream#18]
When calling `get_data_interfaces()` on a `BGPStream` object, the program segfaults.  Minimal example:

```
from _pybgpstream import BGPStream()

stream = BGPStream()
print(stream.get_data_interfaces())
```

The same as a one-liner:

    python -c 'import _pybgpstream; _pybgpstream.BGPStream().get_data_interfaces()'

This is on Debian jessie, with bgpstream 1.1.0 installed from tarball.

gdb shows that a NULL pointer is dereferenced at `src/_pybgpstream_bgpstream.c:199`, which corresponds to https://github.com/CAIDA/bgpstream/blob/master/pybgpstream/src/_pybgpstream_bgpstream.c#L204 (the `info` variable).

**Comment by zorun** [comment]
Note that the data returned by `bgpstream_get_data_interfaces` looks correct:

```
(gdb) print *ids@6
$14 = {BGPSTREAM_DATA_INTERFACE_BROKER, BGPSTREAM_DATA_INTERFACE_SINGLEFILE, 
  BGPSTREAM_DATA_INTERFACE_CSVFILE, BGPSTREAM_DATA_INTERFACE_SQLITE, 
  BGPSTREAM_DATA_INTERFACE_BROKER, 0}
```

**Comment by alistairking** [comment]
Thanks for reporting this. I can reproduce the error and will take a look at what is going on.

**Comment by alistairking** [comment]
This issue should now be fixed in the latest master.
Thanks again for debugging and reporting the problem.

**Comment by eclipsekkk** [comment]
So in the latest version, sqlite interface is not available?

[{'description': 'Retrieve metadata information from the BGPStream Broker service', 'id': 1, 'name': 'broker'}, {'description': 'Read a single mrt data file (a RIB and/or an update)', 'id': 2, 'name': 'singlefile'}, {'description': 'Retrieve metadata information from a csv file', 'id': 3, 'name': 'csvfile'}]
