### ISSUE TITLE
Segmentation fault on pybgpstream

### ISSUE THREAD

**Issue by giorgioM27** [CAIDA/bgpstream#2]
Sometimes, after that my python script is running from a couple of hours i get Segmentation Error:

Cannot open dumpfile http://archive.routeviews.org/route-views.linx/bgpdata/2015.12/RIBS/rib.20151218.1400.bz2: Cannot open dumpfile http://archive.routeviews.org/route-views.sydney/bgpdata/2015.12/RIBS/rib.20151218.1400.bz2: Success
Success
2015-12-19 01:27:23 [error] bgpdump_read_next: incomplete dump record (668 bytes read, expecting 2693)
2015-12-19 01:27:56 [error] bgpdump_read_next: incomplete dump record (236 bytes read, expecting 247)
2015-12-19 01:27:56 [error] bgpdump_read_next: incomplete dump record (44 bytes read, expecting 907)
2015-12-19 01:28:12 [error] bgpdump_read_next: incomplete dump record (89 bytes read, expecting 198)
2015-12-19 01:28:16 [error] bgpdump_read_next: incomplete dump record (1 bytes read, expecting 118)
2015-12-19 01:28:17 [error] bgpdump_read_next: incomplete dump record (1179 bytes read, expecting 1366)
2015-12-19 01:28:21 [error] bgpdump_read_next: incomplete dump record (36 bytes read, expecting 415)
2015-12-19 01:28:22 [error] bgpdump_read_next: incomplete dump record (618 bytes read, expecting 753)
2015-12-19 01:28:24 [error] bgpdump_read_next: incomplete dump record (233 bytes read, expecting 314)
2015-12-19 01:28:29 [error] bgpdump_read_next: incomplete dump record (400 bytes read, expecting 734)
Cannot open dumpfile http://archive.routeviews.org/route-views.isc/bgpdata/2015.12/RIBS/rib.20151218.1600.bz2: Cannot open dumpfile http://archive.routeviews.org/route-views.sydney/bgpdata/2015.12/RIBS/rib.20151218.1600.bz2: Success
Success
Errore di segmentazione

from gdb:
Program received signal SIGSEGV, Segmentation fault.
bgpdump_read_next (dump=0x0) at bgpdump_lib.c:159
159       dump->corrupted_read = false;

Is there a way to fix this?

Thanks

**Comment by alistairking** [comment]
Would you mind posting a minimal python script to reproduce this error?
In the meantime, I'll take a look and see if I can figure out what is going on.

**Comment by alistairking** [comment]
I've pushed a few of our recent fixes to the master branch. 
There are a couple of fixes that may help here:
 - 78a1580cea5b13b74e16be934c2e0223cd826194 fixes a segmentation fault that occurs when a dump file fails to open.
 - c2a24dd91b8ebf3c8287b9ecb3b29dee64c2b03b retries opening dumps a few times in case there is a transient network issue.

Please try building bgpstream from github (from the master branch) and let me know if that helps.

**Comment by giorgioM27** [comment]
the minimal python script is the same of the example on  'https://bgpstream.caida.org/docs/tutorials/pybgpstream'

Ok, i want to try your fix but when I compile the source from git I have received this message:
/bgpstream-master$  ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:254: error: required file 'common/Makefile.in' not found
configure.ac:254: error: required file 'common/libpatricia/Makefile.in' not found
configure.ac:254: error: required file 'common/libinterval3/Makefile.in' not found
configure.ac:254: error: required file 'common/libinterval3/rb_tree/Makefile.in' not found
configure.ac:254: error: required file 'common/libcsv/Makefile.in' not found
configure.ac:254: error: required file 'common/libjsmn/Makefile.in' not found
autoreconf: automake failed with exit status: 1

common dir is empty.

**Comment by alistairking** [comment]
Yes, you need to first update the submodules (thanks for pointing this out, we'll update the docs):

```
$ git submodule init
$ git submodule update
```

**Comment by giorgioM27** [comment]
ok I'm writing all my passes also to help others:
$ sudo pip uninstall pybgpstream (this is the previous package installed on my machine)
$ git clone https://github.com/CAIDA/bgpstream.git
$ git submodule init
$ git submodule update
$ ./autogen.sh 
$ ./configure
$ make
$ sudo make install

The installation process seems good but at this moment is impossible to import:
from _pybgpstream import BGPStream, BGPRecord, BGPElem
ImportError: No module named _pybgpstream

PS: i have also follow the tips of the other guy of copying libwandio.so.1 (sudo cp /usr/local/lib/libwandio.so.1 /usr/lib/libwandio.so.1) that helped me for pip package but not now.

Do you have a suggestion?

**Comment by alistairking** [comment]
The make/make install step does not currently install PyBGPStream.

It should be fine to re-install using pip, otherwise, to install manually:

```
$ cd pybgpstream
$ python setup.py build_ext
$ sudo python setup.py install
```

**Comment by giorgioM27** [comment]
Perfect, thank you! Now is working. 
I'm going to edit my old post and remove the first line. I will tell you here if your new code fix the problem. Thanks in advance

**Comment by alistairking** [comment]
@giorgioM27 did this work for you?

**Comment by giorgioM27** [comment]
Hi, the situation at this moment is:
- fix 78a1580 is working because segfault is not happened
- fix c2a24dd has improved a lot the results

The only thing that i have noted is that sometimes the script never ending and i'm using a timeout to interrupt and return to the main function. Have you noted this?

**Comment by alistairking** [comment]
That sounds like you might be in live mode.

What is time interval that you are using?
Also, are you using the 'set_live_mode()' method?

**Comment by giorgioM27** [comment]
no i'm using a time interval with 'add_interval_filter()' but sometimes never end. Now the timeout is 3 hours, but i have seen that the script can remain blocked all the night or more of 10 hours

**Comment by alistairking** [comment]
Would you mind sharing a copy of the script that you are using so that I can attempt to reproduce the issue?

**Comment by giorgioM27** [comment]
`def get_aspath_bgpstream(item):
    try:
        index = item[0]
        project, start, stop, prefix = item[1]
        bgpstream_aspath = []
        log.info('[{} ASPATH] start operation'.format(str(project).upper()))

        # BGPSTREAM ASPATH: suppress stderr
        devnull = open(constants.error_log_file, 'a')
        oldstderr_fno = os.dup(sys.stderr.fileno())
        os.dup2(devnull.fileno(), 2)

        # BGPSTREAM ASPATH: create a new bgpstream instance and a reusable bgprecord instance
        stream = BGPStream()
        rec = BGPRecord()

        stream.add_filter('record-type', 'ribs')
        stream.add_filter('record-type', 'update')

        # BGPSTREAM ASPATH: consider this time interval:
        stream.add_interval_filter(int(start), int(stop))
        stream.add_filter('project', project)

        # BGPSTREAM ASPATH: start the stream
        stream.start()

        # BGPSTREAM ASPATH: get next record
        while (stream.get_next_record(rec)):
            # BGPSTREAM ASPATH: print the record information only if it is not a valid record
            if rec.status == "valid":
                elem = rec.get_next_elem()
                while (elem):
                    # BGPSTREAM ASPATH: print record and elem information
                    if (elem.fields['prefix'] == prefix):
                        bgpstream_aspath.append((rec.project, rec.collector, rec.type, rec.time, elem.peer_asn,
                                                 elem.fields['prefix'], elem.fields['as-path']))
                    elem = rec.get_next_elem()

        # BGPSTREAM ASPATH: restore stderr
        os.dup2(oldstderr_fno, 2)
        time.sleep(5)

        return bgpstream_aspath

    except Exception, e:
        log.error('[get_aspath_bgpstream] general exception: {}'.format(str(e)))
        return None`

**Comment by giorgioM27** [comment]
def get_aspath_bgpstream(item):
    try:
        index = item[0]
        project, start, stop, prefix = item[1]
        bgpstream_aspath = []
        log.info('[{} ASPATH] start operation'.format(str(project).upper()))

        # BGPSTREAM ASPATH: suppress stderr
        devnull = open(constants.error_log_file, 'a')
        oldstderr_fno = os.dup(sys.stderr.fileno())
        os.dup2(devnull.fileno(), 2)

        # BGPSTREAM ASPATH: create a new bgpstream instance and a reusable bgprecord instance
        stream = BGPStream()
        rec = BGPRecord()

        stream.add_filter('record-type', 'ribs')
        stream.add_filter('record-type', 'update')

        # BGPSTREAM ASPATH: consider this time interval:
        stream.add_interval_filter(int(start), int(stop))
        stream.add_filter('project', project)

        # BGPSTREAM ASPATH: start the stream
        stream.start()

        # BGPSTREAM ASPATH: get next record
        while (stream.get_next_record(rec)):
            # BGPSTREAM ASPATH: print the record information only if it is not a valid record
            if rec.status == "valid":
                elem = rec.get_next_elem()
                while (elem):
                    # BGPSTREAM ASPATH: print record and elem information
                    if (elem.fields['prefix'] == prefix):
                        bgpstream_aspath.append((rec.project, rec.collector, rec.type, rec.time, elem.peer_asn,
                                                 elem.fields['prefix'], elem.fields['as-path']))
                    elem = rec.get_next_elem()

        # BGPSTREAM ASPATH: restore stderr
        os.dup2(oldstderr_fno, 2)
        time.sleep(5)

        return bgpstream_aspath

    except Exception, e:
        log.error('[get_aspath_bgpstream] general exception: {}'.format(str(e)))
        return None

**Comment by giorgioM27** [comment]
`
def get_aspath_bgpstream(project, start, stop, prefix):
    try:
        bgpstream_aspath = []
        log.info('[{} ASPATH] start operation'.format(str(project).upper()))

        # BGPSTREAM ASPATH: suppress stderr
        devnull = open(constants.error_log_file, 'a')
        oldstderr_fno = os.dup(sys.stderr.fileno())
        os.dup2(devnull.fileno(), 2)

        # BGPSTREAM ASPATH: create a new bgpstream instance and a reusable bgprecord instance
        stream = BGPStream()
        rec = BGPRecord()

        stream.add_filter('record-type', 'ribs')
        stream.add_filter('record-type', 'update')

        # BGPSTREAM ASPATH: consider this time interval:
        stream.add_interval_filter(int(start), int(stop))
        stream.add_filter('project', project)

        # BGPSTREAM ASPATH: start the stream
        stream.start()

        # BGPSTREAM ASPATH: get next record
        while (stream.get_next_record(rec)):
            # BGPSTREAM ASPATH: print the record information only if it is not a valid record
            if rec.status == "valid":
                elem = rec.get_next_elem()
                while (elem):
                    # BGPSTREAM ASPATH: get record and elem information
                    if (elem.fields['prefix'] == prefix):
                        bgpstream_aspath.append((rec.project, rec.collector, rec.type, rec.time, elem.peer_asn,
                                                 elem.fields['prefix'], elem.fields['as-path']))
                    elem = rec.get_next_elem()

        # BGPSTREAM ASPATH: restore stderr
        os.dup2(oldstderr_fno, 2)
        time.sleep(5)

        return bgpstream_aspath

    except Exception, e:
        log.error('[get_aspath_bgpstream] general exception: {}'.format(str(e)))
        log.exception(e)
        return None
`

**Comment by alistairking** [comment]
Thanks, would you mind also providing the parameters (`project, start, stop, prefix`) that you are providing to this function.

**Comment by alistairking** [comment]
Is this still a problem for you?

**Comment by giorgioM27** [comment]
Hi  @alistairking, sorry for delay. The problem seems a single event maybe derived from my implementation. I have rewrote some lines of code and now is working correctly. Can close the issue!
Thanks a lot
