### ISSUE TITLE
Remove need for a time window when reading a file

### ISSUE THREAD

**Issue by reuteran** [CAIDA/bgpstream#22]
When using bgpreader to read a file, its a little inconvenient that I have to give it a time window with -w no matter what. Not specifying a time should mean bgpreader reads the whole file.

> $ bgpreader -d singlefile -o rib-file,some-rib-file 
> ERROR: At least one time window must be specified using -w

**Comment by alistairking** [comment]
Agreed.
We'll fix this in an upcoming release.
For now you can specify `-w 0,-2` which will trick BGPStream into reading the entire file.

**Comment by reuteran** [comment]
Cool, the `-w 0,-2` is pretty helpful for now. Thanks

**Comment by alistairking** [comment]
I just committed a change that should allow you to not specify the `-w` option when using singlefile. Let me know if you have any problems.
