### ISSUE TITLE
503 Service Unavailable using bgpreader

### ISSUE THREAD

**Issue by gchaviaras** [CAIDA/bgpstream#28]
Using the following command:
`bgpreader -w <timestamp> -p caida-bmp -k <prefix> -t updates`

I'm getting repeatedly this error:

```
ERROR: Invalid JSON response received from broker
WARN: Broker request failed, waiting 1024s before retry
ERROR: Root object is not JSON
INFO: JSON: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

By the way I'm using `CAIDA OpenBMP` experimental provider that came avaible recenlty after a big 'not working' period. Also I got informed for the provider's status from this page http://bgpstream.caida.org/data

This problem is client-side related or server-side?
Also is there any way to fix it?
Thanks

**Comment by alistairking** [comment]
Sorry, the caida-bmp feed is still experimental (and indeed temperamental), and we've been having a bit of trouble with it.

However, that error doesn't sound like a problem with caida-bmp. Can you please provide the time interval that you are using so that I can reproduce the problem?

**Comment by gchaviaras** [comment]
Yeah sure 
timestamp = 1461567600

**Comment by alistairking** [comment]
Were you only specifying the start time? Or did your time interval have an end time also?
