### ISSUE TITLE
How to access local RIB dump via PyBGPStream

### ISSUE THREAD

**Issue by likesum** [CAIDA/bgpstream#29]
I've learned in the tutorial how to create a BGPStream and customize it using PyBGPStream. But how to read one or several local mrt datafiles and create a BGPStream with PyBGPStream? Is there any simple example?

**Comment by alistairking** [comment]
We don't have an example explicitly for PyBGPStream, but you should be able to adapt the BGPReader example (http://bgpstream.caida.org/docs/tutorials/bgpreader#other) fairly easily.

You'll want to use the `set_data_interface` and `set_data_interface_option` methods (http://bgpstream.caida.org/docs/api/pybgpstream/_pybgpstream.html#_pybgpstream.BGPStream.set_data_interface) to select the `singlefile` data interface, and then set the `upd-file` and `rib-file` options.

**Comment by alistairking** [comment]
I'll close this as it's not strictly an issue, but please feel free to continue to ask questions on this thread if you have any problems.

**Comment by alistairking** [comment]
You'll want to use some code like this before "starting" the stream:

```
stream.set_data_interface("singlefile")
stream.set_data_interface_option("singlefile", "rib-file", PATH_TO_RIB)
```

Does that help?

**Comment by arashmolavi** [comment]
Yes! Thank you so much!
