### ISSUE TITLE
[feature] time interval filter in reverse

### ISSUE THREAD

**Issue by digizeph** [CAIDA/bgpstream#31]
It would be nice if BGPStream can get data in reverse within a time interval. For example, if we set a `start_time` and a `end_time`, BGPStream will fetch updates and entries sorted by time from `end_time` to `start_time`. Or people can set only the `end_time` and stop fetching when their needs are met.

This would be very useful in cases like BGP forensics study where people would look back in time see what related updates were announced.

**Comment by alistairking** [comment]
This is an interesting idea.
Overall it shouldn't be very complicated to get files sorted in reverse order, but it may prove trickier to extract records from dump files in reverse order.
If you're interested in pursuing it, we'd love you to submit a PR.
