### ISSUE TITLE
no wget on OSX

### ISSUE THREAD

**Issue by smlng** [CAIDA/bgpstream#4]
Hi,

the install instruction for OSX are incomplete/faulty, as there is no `wget` available per default. 

You may either change downloads for `wandio` and `bgpstream` into
```
curl -O http://research.wand.net.nz/software/wandio/wandio-1.0.3.tar.gz
curl -O http://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/bgpstream-1.0.0.tar.gz
```

or install `wget` instead
```
sudo port install wget
```

**Comment by alistairking** [comment]
Thanks. I'll update the website.
