### ISSUE TITLE
bgpstream ./configure fails because of missing libwandio

### ISSUE THREAD

**Issue by rbirkner** [CAIDA/bgpstream#41]
I am trying to install **bgpstream core** on Mac OS X and am following the steps. it seems like I successfully managed to install `libwandio` as `$ wandiocat http://google.com` works.

However, when trying to run `$ ./configure`, I get the following error:

> checking for library containing wandio_create... no
> configure: error: libwandio required (http://research.wand.net.nz/software/libwandio.php)

**Comment by alistairking** [comment]
Hmm, that is strange.

What OS are you using?
Can you also please attach your `config.log` file?

**Comment by rbirkner** [comment]
sorry for the late reply:
the OS is macOS Sierra 10.12.3
and this is the file [config.log.txt](https://github.com/CAIDA/bgpstream/files/782533/config.log.txt)

**Comment by rbirkner** [comment]
sorry for the late reply!
the OS is macOS Sierra 10.12.3
this is the config file [config.log.txt](https://github.com/CAIDA/bgpstream/files/782537/config.log.txt)

**Comment by alistairking** [comment]
Thanks!
Would you mind trying setting `C_INCLUDE_PATH` and `LIBRARY_PATH` before running `configure` like so (I presume you installed wandio in the default location):
```
export C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH"
export LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
```
Let's see if that helps.

If it doesn't fix things for you, can you run:
```
otool -L `which wandiocat`
```
and paste the output here.

**Comment by rbirkner** [comment]
works like a charm. thanks a lot for your immediate help!

**Comment by alistairking** [comment]
No problem. 
It's an unfortunate "feature" in macOS where `/usr/local/lib` isn't in the default search path for the linker.
I'll update the install documentation to mention this fix.
