### ISSUE TITLE
Filtering a stream against communities returns state messages

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#42]
I would expect that when applying the `community` filter on a stream, namely the following code

```
stream = BGPStream()
stream.add_filter('community', community)
```

should return only BGP records that are annotated with the specified communities. Such records can be only Announcements and RIB elements. However, I observed that State BGP messages are also returned although they don't have the `community` attribute. Shouldn't they be filtered-out?

**Comment by alistairking** [comment]
I'm pretty sure this was a design decision that we made, though I can't remember the motivation. Maybe @chiaraorsini can help us.

Either way, I'll leave this issue open to remind us to come up with a better solution.

**Comment by chiaraorsini** [comment]
State and withdrawal messages are not filtered on purpose (see ref. below).

The design decision was based on the idea that if the user wants to maintain some state associated with the communities observed (e.g. how many prefixes are currently labeled with a community, for how long is community attribute used, etc...) withdrawal and state messages are required to infer such state.


https://github.com/CAIDA/bgpstream/blob/1115a80ee587d58528ba64aeeebff50c555faefb/lib/bgpstream_record.c#L288 
` /* Checking communities (unless it is a withdrawal message) */`

**Comment by vgiotsas** [comment]
The problem is that to monitor the state of prefixes labeled with specific communities one has to also monitor announcements for the prefixes tagged with a community, because a community can be changed not just with an explicit withdrawal but also with a re-advertisment of a prefix with different community values.

**Comment by digizeph** [comment]
Seems like the behavior conforms with the design. I'm going to close this issue for now. Please feel free to re-open if you would like to have further discussions.
