### ISSUE TITLE
./configure error wandio

### ISSUE THREAD

**Issue by SamAchten** [CAIDA/bgpstream#43]
While installing wandio I keep getting this error when I run ./configure.

make[2]: Map '/mnt/c/Users/Sam/Downloads/wandio-1.0.3/lib' wordt binnengegaan
  CCLD   libwandio.la
/usr/bin/ld: //usr/local/lib/libbz2.a(bzlib.o): relocation R_X86_64_32S against `BZ2_crc32Table' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libbz2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

I'm on Ubuntu 16.04

Thank you

**Comment by alistairking** [comment]
It seems that you only have the static library available for bz2.
Have you installed libbz2-dev ?
i.e. `sudo apt-get install libbz2-dev`

**Comment by alistairking** [comment]
Did you managed to figure this out?

**Comment by alistairking** [comment]
I'm going to close this for now. Please feel free to reopen if you're still having problems.
