### ISSUE TITLE
[Feature] more stream filter options

### ISSUE THREAD

**Issue by yang-dev** [CAIDA/bgpstream#45]
these stream filters options can be quite handy
- address family -> analysis of data is usually done separately for v4 and v6
- as_path regex -> full feature partial regex match
- collector peer IP, with a negative switch

`-j` filters router collector peer ASN, documentation sounds a bit like origin ASN

Is it feasible to include extended communities (PA 16), large_community (PA 32)?

**Comment by romain-fontugne** [comment]
I also would love to see filters for address family and peer IP

**Comment by alistairking** [comment]
Thanks for the feature request. We have recently merged some code into the master branch that provides a nicer filter interface, and includes an AS Path regex feature. See https://github.com/CAIDA/bgpstream/blob/master/FILTERING for more information.

As for address family, and peer IP, we'll make sure they are in the next release (of course PRs are always welcome).
In the meantime, you can filter to v4 and v6 by specifying "0.0.0.0/0" and "::0/0" respectively as prefix filters.

**Comment by alistairking** [comment]
And yes, I just personally ran into the `-j` documentation bug. Thanks for pointing that out.

**Comment by digizeph** [comment]
This issue was moved to CAIDA/libbgpstream#42
