### ISSUE TITLE
entry is truncated/ attribute is truncated message in output

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [CAIDA/bgpstream#47]
`bgpreader -p routeviews -t updates -w 1373735144,1373994344 -k 84.116.0.0/16`, the following warning message was shown in results. Is this because of RIB dump format change on routeviews?

>2017-07-11 12:14:23 [warn] entry is truncated: expected=4071 remaining=4069
>2017-07-11 12:14:23 [warn] ERROR attribute is truncated: expected=4067 remaining=4065

**Comment by alistairking** [comment]
This is usually seen when processing a corrupted (e.g., truncated) dump file.

I'm running the command you posted, but it covers a huge number of dump files: all update files for all RV collectors for 3 days (~4300 if i did the math right). 

Any chance the logs you have also include a dump file name? Or can you narrow the time window down?

**Comment by alistairking** [comment]
I'm going to assume that you figured this out. Feel to reopen if you are still having the problem.

**Comment by LukeFenton** [comment]
Hi, I have been receiving MRT files from an external source and using BGP Reader to parse these files. I have been getting the warning - 

    [warn] ERROR attribute is truncated: expected=77 remaining=43

    [warn] process_one_attr failed, stopping attribute processing

This has happened on multiple files and from research I am guessing there could be something wrong with the file itself. Is there anyway to narrow down whether a file is corrupt or a better way to debug this.

The file processes partially and then stops once this warning is displayed. The files are converted from base64 strings after being received.

Any help or advice would be appreciated :smile: 

Luke

**Comment by LukeFenton** [comment]
I've attached an example file which is causing the issue if that helps. There are a lot of these which are causing the warning - 

[Truncated_MRT.zip](https://github.com/CAIDA/bgpstream/files/3108179/Truncated_MRT.zip)

**Comment by alistairking** [comment]
I'm pretty sure that's not an MRT file. I think you might be doing the conversion from hex incorrectly.

**Comment by LukeFenton** [comment]
Apologies that one seems to be the base64 version of the MRT. This is the file decoded from base64. This gives me the error -

    [warn] ERROR attribute is truncated: expected=136 remaining=4

I have attached the file decoded below-

[Truncating_mrtFile.zip](https://github.com/CAIDA/bgpstream/files/3112835/Truncating_mrtFile.zip)

**Comment by alistairking** [comment]
Yes, it certainly seems that that file contains corrupted data. I tried it with libparsebgp (the new parser we have in v2) and it also agrees that there is corrupted data.

**Comment by LukeFenton** [comment]
Hi,

Thanks very much for this...I am guessing that the parser will work until it find an issue which knocks it out of play and then stops processing the rest of the file?

I don't suppose you would have come across messages which do not seem to comply with anything I have seen before -

  ```A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|200.0.0.0/14|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|32.1.5.121/36|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|32.1.5.123/36|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|1.1.2.64/64|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|0.0.0.0/0|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|0.0.0.0/0|255.255.255.255|||||
U|A|1549167080|singlefile_ds|singlefile_ds|65003|2a00:2381:36e:2300:2a2:eeff:fe51:1961|40.0.0.0/11|255.255.255.255|||||

I am unsure what is cauing these messages and others like them to show an IPv6 PeerIP and a prefix of greater that >/32 in IPv4 format.

Some strange behaviour but I am unsure whether it is my MRT or something which is expected.

Thanks

L

**Comment by alistairking** [comment]
Yeah, corrupt data means that the parser (normally) cannot continue past the corruption so the rest of the file is unreadable. Since this happens relatively frequently (dumps get corrupted for a variety of reasons), we have configured BGPStream to just move on to the next dump file.

Those records do seem pretty strange. @kenkeys would you mind taking a look at this data? (even if it is corrupted data, should we error out if we see prefix lengths >32?)

**Comment by alistairking** [comment]
Oh, @kenkeys this looks like BGPStream v1. Not sure what the v2 parser does in this case.

**Comment by LukeFenton** [comment]
Hi, these weird messages aren’t in the MRT I uploaded...I have isolated them and can upload this tomorrow.

**Comment by alistairking** [comment]
Oh yes, thanks. That would be helpful.

**Comment by LukeFenton** [comment]
Hi, here is the file which is producing the >/32 prefixs
[greater_than_slash_32.zip](https://github.com/CAIDA/bgpstream/files/3116031/greater_than_slash_32.zip)

**Comment by LukeFenton** [comment]
Here is another file which contains more >/32 messages.

[Above32Prefix.zip](https://github.com/CAIDA/bgpstream/files/3116992/Above32Prefix.zip)

**Comment by LukeFenton** [comment]
And finally I have tried another Parsing tool by user t2mune, and the tools in this [project](https://github.com/t2mune/mrtparse). The results are different and do not show the 0.0.0.0/0 files or the >/32 prefixes. The results have come from the last zip file MRT I posted. I hope this information is helpful in someway.

[OtherParserResults.zip](https://github.com/CAIDA/bgpstream/files/3117227/OtherParserResults.zip)
