### ISSUE TITLE
-k -y filter not working as expected

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [CAIDA/bgpstream#48]
- default is matched for every prefix filter?
- community filter is not working
- RIB begin/end message in output is not useful when filter is applied

```
$ bgpreader -p routeviews -w 1405530344,1405789544 -k 84.116.0.0/16 -y 1299:30000
R|B|1405533600|routeviews|route-views.perth
R|E|1405533600|routeviews|route-views.perth
R|B|1405533600|routeviews|route-views.kixp
R|E|1405533600|routeviews|route-views.kixp
R|B|1405533600|routeviews|route-views.linx
R|R|1405533600|routeviews|route-views.linx|31500|195.66.224.215|0.0.0.0/0|195.66.224.215|31500 3216|3216|||
R|R|1405533600|routeviews|route-views.linx|3561|195.66.224.39|0.0.0.0/0|195.66.224.39|3561|3561|||

```

Is it possible to support logical operators with filters (AND/OR community)?

**Comment by alistairking** [comment]
Yeah, the current filter implementation is known to be very limited. 

PR #6 added a new filter implementation which is currently available in the master branch on GitHub if you want to try it, and it adds some richer filter types and a BPF-like syntax.

Preliminary documentation for this is here: https://github.com/CAIDA/bgpstream/blob/master/FILTERING

It currently does not fully support AND/OR logic, but if you'd like to submit a PR adding that feature, that would be great!

As for the begin/end messages not being useful, I think their usefulness depends on ones use case. For code that needs to know when a RIB begins and ends (e.g., when inferring a peer's routing table), they are necessary. Again, ideally this should be something specified using a richer filter syntax, but for the moment we have erred on the side of giving as much information as possible, assuming that the user can simply ignore those records they are not interested in.

**Comment by alistairking** [comment]
Also see Issue #42 for a related discussion about why the begin/end messages are included.

**Comment by alistairking** [comment]
I'm going to close this for now. Feel free to reopen if you feel like I haven't addressed your comments.
