### ISSUE TITLE
Segmentation fault when calling BGPStream.get_data_interfaces()

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#50]
As the title says, when I call the [get_data_interfaces()](http://bgpstream.caida.org/docs/api/pybgpstream/_pybgpstream.html#_pybgpstream.BGPStream.get_data_interfaces) method of the BGPStream class I get segmentation fault. If you want to reproduce the error, this is what I did:

```
Python 2.7.12 (default, Jul 18 2016, 15:02:52)
[GCC 4.8.4] on linux2
>>> from _pybgpstream import BGPStream
>>> stream = BGPStream()
>>> stream.get_data_interfaces()
Segmentation fault (core dumped)
```

I tried it in another machine (Python 2.7.9) with the same result.

**Comment by digizeph** [comment]
Has this issue been resolved yet?

**Comment by alistairking** [comment]
@digizeph i'm not sure. If you're interested, I can get you a copy of pybgpstream v2 to test.

**Comment by digizeph** [comment]
@vgiotsas this issue has been addressed in the master branch and will be included in the upcoming v2 release. 
In the mean time, you can compile and install `pybgpstream` using source code [here](https://github.com/CAIDA/bgpstream/tree/master/pybgpstream) to avoid this problem.
```
$ python setup.py build
# python setup.py install
```
