### ISSUE TITLE
BGPStream crashes for BGP updates during specific period. 

### ISSUE THREAD

**Issue by aqibn** [CAIDA/bgpstream#52]
Hi, I'm trying to fetch updates during the interval 1466877600 (June 25th 6:00PM UTC) to 1466917200 (26th June 5:00AM) for the following prefixes below: 

198.41.0.4/24
192.228.79.201/24
192.203.230.10/24
192.58.128.30/24
8.8.8.0/24

stream.add_filter('project','routeviews')
stream.add_filter('project','ris');
stream.add_filter('record-type','updates')

However BGPstream seems to crash while fetching updates for all prefixes during this defined period. Same script works for other periods. Is this a problem with the datasource for the BGP updates. 

I'm running it on Ubuntu.

**Comment by alistairking** [comment]
Hey, 

Thanks for reporting this.
I remember coming across a similar problem earlier this year, and in that case it had to do with the MRT-parser crashing on some corrupted dump files, but I just ran bgpreader across the time range you specified and it seemed to run fine.

Do you have any output from BGPStream when it crashes?

**Comment by aqibn** [comment]
I'm using pybgpstream where I'm running a simple script which fetches updates from RouteViews and RIPE RIS for the following prefix and time period. I get the following output below:

python print-prefix.py 8.8.8.0/24 1466877600 1466917200
G 8.8.8.0/24 1466877600 1466917200
.....
.....
routeviews|route-views4|update|valid|1466885989|A|36236|208.111.38.185|8.8.8.0/24|208.111.38.185|36236 15169
routeviews|route-views2|update|valid|1466888413|A|8492|85.114.0.217|8.8.8.0/24|85.114.0.217|8492 15169
routeviews|route-views2|update|valid|1466888501|A|8492|85.114.0.217|8.8.8.0/24|85.114.0.217|8492 15169
ris|rrc03|update|valid|1466891225|A|50763|80.249.210.99|8.8.8.0/24|80.249.210.99|50763 15169
Killed


With bgpreader: 

bgpreader -w 1466877600,1466917200 -p routeviews -p ris -t updates -k 8.8.8.0/24
...
...
...
U|S|1466891997|ris|rrc03|20747|80.249.208.145||||||CONNECT|OPENSENT
U|S|1466891997|ris|rrc03|20747|80.249.208.145||||||OPENSENT|ACTIVE
U|S|1466891999|ris|rrc10|12399|217.29.66.83||||||ACTIVE|CONNECT
U|S|1466892000|ris|rrc04|2613|192.65.185.230||||||ACTIVE|CONNECT
Killed

As you can see I get some updates before the process gets killed. 


It is interesting as this only happens when I fetch updates from both RIS and RouteViews at the same time while it works if I fetch from one provider only.

**Comment by alistairking** [comment]
Oh. This sounds more like you're running out of memory.

Can you try running your script like this:
```
LIBTRACEIO=nothreads python print-prefix.py 8.8.8.0/24 1466877600 1466917200
```

and see if that helps?

**Comment by aqibn** [comment]
It worked. 

Thanks.
