### ISSUE TITLE
Feedback wanted: pybgpstream community structure

### ISSUE THREAD

**Issue by alistairking** [CAIDA/bgpstream#54]
We're currently working on the v2 release of BGPStream, and I want to get some feedback on how you would like to see the community data structured in the python bindings.

Currently we turn a community set into a list of dictionaries, where each dictionary has `asn` and `value` keys.

Is this too cumbersome?
Would folks prefer a simple list of `:`-separated strings?
Or something else?

If I don't hear anything, then we'll keep the current structure, so speak now or forever hold your peace :)

**Comment by alistairking** [comment]
@vgiotsas i know you've used pybgpstream a lot with communities data. Do you have any thoughts about this?

**Comment by vgiotsas** [comment]
Hey @alistairking thanks for asking. Yes I think the format should be changed to a list of strings, in most cases the Community values make sense only as a whole.

Also it would be great to add support for alternative community formats such as Large Communities: 

https://tools.ietf.org/html/rfc8092

I can help with some tasks if you need extra hands.

**Comment by alistairking** [comment]
Thanks @vgiotsas.

We are actually switching to a new BGP parser in v2, which (in addition to being much faster) has support for Large Communities and to some extent, Extended Communities, so it would be pretty easy to make this data available in BGPStream. I'll add it to my todo list.

Thanks for your offer. I should have a beta version ready within the next couple of weeks, so if you'd be interested in doing some testing, that would be much appreciated.

**Comment by vgiotsas** [comment]
For sure, thanks a lot.

**Comment by alistairking** [comment]
It occurs to me.. What about making it a set of strings rather than a list. This would make answering "does this elem have community x?" more efficient I suspect.

**Comment by vgiotsas** [comment]
Yes, that's a good idea, each Community value should be unique so a set makes more sense.
