### ISSUE TITLE
Query over two time windows does not work as expected

### ISSUE THREAD

**Issue by salsh** [CAIDA/bgpstream#57]
If a query is made over two time windows, it does not always work as expected. The expected result should be processing through both time windows one after the other if the necessary BGP data are available, right?

The following query works as expected:
`bgpreader -t updates -p ris -c rrc00 -w 1502352000,1502352100 -w 1502353000,1502353100`

The following query ends after the first time window although there are BGP data for the second time window:
`bgpreader -t updates -p ris -c rrc00 -w 1502340000,1502340100 -w 1502350000,1502350100`

I hope the potential bug only applies to this version. I am very much looking forward to the next release.

**Comment by alistairking** [comment]
I was wondering when someone would try and use this feature :)
I'm not sure that we've ever really tried it. I'll send you an email about testing an early beta of the next release so that we can see if the problem is still present.

**Comment by salsh** [comment]
I asked myself the same question :) I only tested the feature so the ROAFetchlib supports it.

Thanks for the e-mail.

**Comment by digizeph** [comment]
This issue was moved to CAIDA/libbgpstream#44
