### ISSUE TITLE
BGPStream successfully installed on Windows 10

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#58]
I successfully installed BGPStream on Windows 10 using the [Linux Subsystem ](https://docs.microsoft.com/en-us/windows/wsl/about) with the [Ubuntu for Windows](https://www.microsoft.com/el-gr/store/p/ubuntu/9nblggh4msv6?rtc=1) distribution. 

After [activating](https://docs.microsoft.com/en-us/windows/wsl/install-win10) the Linux Subsystem just follow the BGPStream [installation instructions](https://bgpstream.caida.org/docs/install/bgpstream) for Ubuntu.

**Comment by digizeph** [comment]
Thank you @vgiotsas for testing it out 😄 
I created an issue for adding documentation for BGPStream Windows 10 installation at CAIDA/libbgpstream#43.
