### ISSUE TITLE
Add route-views.napafrica collector

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#59]
RouteViews recently added a new collector at NAPAfrica (South Africa):
http://www.routeviews.org/napafrica.html

Is it possible to add the `route-views.napafrica` collector to the available set of BGPStream collectors?

**Comment by alistairking** [comment]
Thanks for pointing this out. 

I've added it to the BGPStream index, but it seems that the only data available is from Februrary. I've reached out to the Route Views folks, so if/when they fix the problem, the new data will also be available via BGPStream.
