### ISSUE TITLE
get_next_record stop returning values before end of interval and stay blocked

### ISSUE THREAD

**Issue by ksalamat** [CAIDA/bgpstream#60]
Hello, 
I am using the pybgpstream library over past collectors data (no real time) and I have frequently the get_next_record function getting blocked before end of interval. Was wondering if it is not that the broker is busy. If it is the case would be useful to have a exception returned so the code can manage the issue.

**Comment by alistairking** [comment]
That is unusual. 
Can you give some more context? 
E.g.:
 - What collectors are you using? 
 - What time interval? 
 - How long does it block for?
 - Do you see any messages on stderr?

**Comment by alistairking** [comment]
I'm going to close this issue. Please feel free to re-open if you still want assistance with this problem.
