### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by belfare** [CAIDA/bgpstream#64]
I got this error:
Assertion failed: (! attr->community), function process_one_attr, file bgpdump_lib.c, line 900.

Command: bgpreader -w1524839059

Version: 1.1.0
Compiled on: macOS High Sierra (up to date at time of this ticket)

**Comment by digizeph** [comment]
Hey @belfare, thank you for submitting this issue. 

I am trying to repeat the problem, but need your help on narrowing down the range of data. It seems like the problem happens around time 1524844800.

Could you try `./bgpreader -w1524844790,1524844810` to see if you could still see the problem?

In the mean time, I am running the same thing on my mac environment:
macOS 10.13.4, and master branch 1115a80ee587d58528ba64aeeebff50c555faefb

**Comment by digizeph** [comment]
@belfare there have been some bug fixes since the release 1.10. Could you actually try to run the version on the master branch?

**Comment by aisavnin** [comment]
Also support this question.
Such bug appeared on 22nd of March.
Reappears on daily run python script with pybgpstream, analyzing 8 hours of data.

**Comment by belfare** [comment]
I'll pull the master and compile/run.

**Comment by belfare** [comment]
I was able to get past the point where it was erroring out prior.  Can someone update the tarball on the .org site?  That's the one I pulled for what I believed was the latest known good candidate.

Thanks agian!

**Comment by alistairking** [comment]
I'm going to assume that this solved the problem and close the issue. Feel free to re-open if you're still having problems.
