### ISSUE TITLE
Wandio HTTP support error

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#70]
I'm trying to install BGPStream on CentOS Linux 7.4.1708.

I installed Wandio 1.0.4 with all the necessary libraries:

```
configure: WANDIO version 1.0.4
configure: Compiled with compressed file (zlib) support: Yes
configure: Compiled with compressed file (bz2) support: Yes
configure: Compiled with compressed file (lzo write only) support: Yes
configure: Compiled with compressed file (lzma) support: No
configure: Compiled with http read (libcurl) support: Yes
```
When I try to configure libbgpstream I get the following error:

`wandio HTTP support required. Ensure you have a working Internet connection and that libcurl is installed before building wandio`

When I run `wandiocat google.com` it fails to open the site:
 
`Failed to open google.com`

However `curl google.com` runs without problem. Can it be a firewall issue?

**Comment by alistairking** [comment]
Have you seen the CentOS-specific install notes that deal with this error message on the Cent OS tab of http://bgpstream.caida.org/docs/install/bgpstream

**Comment by digizeph** [comment]
@vgiotsas can you try `wandiocat http://www.google.com` I believe the http headers are necessary for wandiocat.

**Comment by vgiotsas** [comment]
Thanks @digizeph it works!
So now the "mystery" is why BGPStream configuration fails with error `wandio HTTP support required`

**Comment by digizeph** [comment]
@vgiotsas Can you try run `sudo ldconfig` after installation and see if you still see the same problem? It's possible that the shared libraries are not immediately recognized by the system after installation.

**Comment by vgiotsas** [comment]
@digizeph I edited my reply, it works now, thanks again!
