### ISSUE TITLE
Get records starting from latest RIB

### ISSUE THREAD

**Issue by danizord** [CAIDA/bgpstream#75]
Hey! First of all thanks for this awesome project!

Not sure here is the right place for questions, please tell me if it is not :)

Here's my question: Is there any way to tell `bgpreader` to start reading from latest RIB of each collector then continue with each update after the RIB snapshot?

Thanks in advance :)

**Comment by alistairking** [comment]
I'm glad you like it!
This is as good a place as any to ask questions.

So, no, there's not exactly a way to do what you're asking, but you can get relatively close by calculating yourself the most recent hour that all RV and RIS collectors would have published a RIB (i.e., the most recent 00:00, 08:00, 16:00), and start from that time.

If you don't want to receive RIB information after this first table, you can use the `-P` (RIB period) option:
```
 -P, --rib-period             <period>         process a rib files every <period> seconds (bgp time)
```
 with a really large value. If you were using the API, then I'd suggest `-1` to force an integer overflow and give you a huge value, but it seems that bgpreader doesn't like that.
When we do this kind of thing we normally want to get a RIB every now and again, so we pick some large, but not huge value, e.g., 1 day (86400).

Hope this helps!

**Comment by danizord** [comment]
@alistairking great! I tried starting from 00:00, 08:00 and 16:00 and it works fine. Though I'm not sure the `--rib-period` is helping me, since I'd like to have the `bgpreader` running indefinitely for several days.

My actual use case is to download the RIB and keep listening for updates so that I can detect BGP hijacks for my prefixes.

I think the easier approach would be to first download and parse the RIBS manually, then use `bgpreader` to listen for updates only. What do you think?

Appreciate your attention :)

**Comment by alistairking** [comment]
In that case you might want to try the PyBGPStream python API and parse the RIBs with one instance of BGPStream and then handle the updates with another.
But I still think that the RIB period option could be useful in either case since this way you will effectively get a "sync" now and again (e.g., in case there were some missed updates, the period RIB dump will help mitigate this)

**Comment by alistairking** [comment]
I'm going to close this issue for now. Feel free to re-open if you have further questions.
