### ISSUE TITLE
No updates retrieved for certain collectors/periods

### ISSUE THREAD

**Issue by albertogarciam** [CAIDA/bgpstream#78]
Hi,
Thanks for your effort developing this tool!

I'm having trouble donwloading updates for certain collectors/periods. 
For example, rrc18, oct 2016.
I go to `http://data.ris.ripe.net/rrc18/2016.10/`, download `updates.20161001.0000.gz`, and I see many updates. 
Then, I try `pybgpstream-1.2.1`, with a modified version of your `pybgpstream-print.py` example code with an interval filter `1475280005,1475280032`, for which I know there are updates, according to the updates file above:
```
from _pybgpstream import BGPStream, BGPRecord, BGPElem

stream = BGPStream()
rec = BGPRecord()

stream.add_filter('collector','rrc18')
stream.add_interval_filter(1475280005,1475280032)

stream.start()
while(stream.get_next_record(rec)):
    if rec.status != "valid":
        print ('Invalid: {}, {}, {}, {}, {}'.format(rec.project, rec.collector, rec.type, rec.time, rec.status))
    else:
        elem = rec.get_next_elem()
        while(elem):
            print(rec.project, rec.collector, rec.type, rec.time, rec.status, elem.type, elem.peer_address, elem.peer_asn, elem.fields)
            elem = rec.get_next_elem()
```

This returns nothing. If I change the code for other rrc, e.g., rrc10, it prints many updates, so I think it is not a local problem in my configuration. (rrc20 does not retrieve data for this period either).

I have found this to happen in other rrc's/years.
Any idea? Thanks!

**Comment by albertogarciam** [comment]
Digging a bit on the problem, it seems the problem is the info returned by the data broker.
No files pointed by when rrc18 is queried
<https://bgpstream.caida.org/broker/data?human&intervals[]=1475280005,1475280032&collectors[]=rrc18&types[]=updates>
While it does report files to download the data when rrc00 is queried
<https://bgpstream.caida.org/broker/data?human&intervals[]=1475280005,1475280032&collectors[]=rrc00&types[]=updates>

I assume that the data broker should report for the `rrc18` case the file that it does exist in <http://data.ris.ripe.net/rrc18/2016.10/>. 
Is there any way of having this corrected in the meta data repository?
(Less desirable,) Otherwise, is there an easy way of locally circumventing this (in case the meta data repository  does not report a link, to generate the link with local code?)

**Comment by alistairking** [comment]
Hi! Thanks for using BGPStream, and thanks for the detailed bug report. This is really helpful.
This does seem to be a problem with the meta data from the broker. I'll dig a bit more and see what I can find.

**Comment by alistairking** [comment]
Ok, I looked into this and confirmed that this was an indexing issue. RRC18 (and higher) are collectors that have been added after the BGPStream project started, and we appear to have not indexed data prior to the point when we added them to our crawler. I'll work on backfilling our metadata, but this is a relatively slow process. In the meantime, you can check the "First Dump" column on http://bgpstream.caida.org/data#!ris to see when our metadata indexing began (RRC18 now shows October 2016 as I have started the process of filling in data for it).

**Comment by albertogarciam** [comment]
Thanks for your extremely fast answer and support

**Comment by alistairking** [comment]
I've since completed a full sweep of all RV and RIS collectors, so I think this issue can now be closed. Feel free to reopen if you have any further concerns.
