### ISSUE TITLE
24 Hours with no messages

### ISSUE THREAD

**Issue by LukeFenton** [CAIDA/bgpstream#88]
Hi,

Ingest of messages stopped at 13:00UTC 2019/05/01. According to the bgpstream website there have been 0 message dumps.

I don't know whats causing this issue and there is no news about maintenance windows etc.

Can you let me know if this is going to be a long term outage?

Thanks in advance

Luke

![image](https://user-images.githubusercontent.com/26971720/57067532-3a111300-6cc7-11e9-9867-c712f9f0ba9b.png)

**Comment by alistairking** [comment]
It looks like one of our backend database servers has failed. I'm trying to get it back online now.
Apologies for the inconvenience.

**Comment by alistairking** [comment]
Ok, looks like we're back online.
