### ISSUE TITLE
Can't find libcurl on CentOS 7

### ISSUE THREAD

**Issue by ewosborne** [CAIDA/bgpstream#9]
I'm having trouble compiling wandio with HTTP support.  libcurl is in my ldconfig path:

sudo ldconfig -p | grep url
        libcurl.so.4 (libc6,x86-64) => /usr/lib64/libcurl.so.4

but it still fails to build with URL support:

configure: WANDIO version 1.0.3
configure: Compiled with compressed file (zlib) support: Yes
configure: Compiled with compressed file (bz2) support: Yes
configure: Compiled with compressed file (lzo write only) support: No
configure: Compiled with compressed file (lzma) support: No
configure: Compiled with http read (libcurl) support: No

What else should I try?

**Comment by ewosborne** [comment]
Fixed: I needed to install libcurl-devel, not just libcurl.

**Comment by alistairking** [comment]
I'm glad you figured it out!
