### ISSUE TITLE
Specify multiple local files for the singlefile data interface

### ISSUE THREAD

**Issue by listenerri** [CAIDA/bgpstream#90]
Here are the options I have tried:

```
./bgpcorsaro \
-d singlefile \
-o rib-file,/data/bview.20190616.0000.gz \
-o upd-file,/data/updates.20190616.0000.gz \
-o upd-file,/data/updates.20190616.0005.gz \
-o upd-file,/data/updates.20190616.0010.gz \
-o upd-file,/data/updates.20190616.0015.gz \
... other options ...
```

But only `bview.20190616.0000.gz` and the last updates file `updates.20190616.0015.gz` was accept by bgpstream, is there any way to get all the specified files accepted?

**Comment by alistairking** [comment]
The singlefile interface is designed for just that, a single file of each type.
You might want to try the CSV data interface which allows you to provide more files, and more information about the files.
There is a sample CSV file here: https://github.com/CAIDA/bgpstream/blob/master/test/csv_test.csv

**Comment by listenerri** [comment]
Hi @alistairking, sorry for this late reply, I have been tested the csvfile datasource and as you said that is fully meet my needs, I' m closing this issue, thanks a lot. 

But I still not understand what does the last two columns mean in `csv_test.csv` file.

**Comment by alistairking** [comment]
The second-to-last field is the duration of the file -- that is, how many seconds of data are contained.
The last field is the time that the file was added to the CSV file. This is used when using the CSV to process "live" data where you periodically append new rows to the file.

**Comment by listenerri** [comment]
Ok, I get it now, thanks！
